controller:
  installPlugins:
    - kubernetes:3900.va_dce992317b_4
    - workflow-aggregator:596.v8c21c963d92d
    - configuration-as-code:1647.ve39ca_b_829b_42
    - git:5.1.0
  additionalPlugins:
    - github-api:1.314-431.v78d72a_3fe4c3
    - github:1.37.1
    - github-branch-source:1725.vd391eef681a_e
  JCasC:
    configScripts:
      default-security: | #can be any name, the content will be picked up by Jenkins
        jenkins:
          securityRealm:
            local:
              allowsSignup: false
              enableCaptcha: false
              users:
                - id: "admin"
                  name: "Jenkins configScripts Admin"
                  password: "admin123"
          authorizationStrategy: 
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false
      # global-creds: |
      #   credentials:
      #     system:
      #       domainCredentials:
      #         - credentials:
      #             - usernamePassword:
      #                 scope: GLOBAL
      #                 id: "github-org"
      #                 username: 
      #                 password: 
      #                 description: "Username/Password Credentials for org authentication"